name = "high-distortion-music-app3"
main = "src/worker.js"
compatibility_date = "2024-08-06"

[env.production]
name = "high-distortion-music-app"

[env.staging]
name = "high-distortion-music-app-staging"

# Environment variables (optional)
[vars]
ENVIRONMENT = "production"
APP_NAME = "High Distortion Music App"
VERSION = "1.0.1"

# Add custom domains here if you have any
# [[route]]
# pattern = "music.yourdomain.com/*"
# zone_name = "yourdomain.com"